In [2]:
import matplotlib.cm
import h5py
import yt
import numpy as np
import despotic

In [4]:
# f = h5py.File('../data/hdf5/snapshot_030.hdf5', 'r')
ds = yt.load('../data/hdf5/snapshot_030.hdf5')

# inspect the data
ds.field_list
# ds.derived_field_list

yt : [INFO     ] 2022-08-02 10:12:29,509 Calculating time from 7.500e-01 to be 3.063e+17 seconds
yt : [INFO     ] 2022-08-02 10:12:29,513 Assuming length units are in kpc/h (comoving)
yt : [INFO     ] 2022-08-02 10:12:29,620 Parameters: current_time              = 3.0631142745450496e+17 s
yt : [INFO     ] 2022-08-02 10:12:29,623 Parameters: domain_dimensions         = [1 1 1]
yt : [INFO     ] 2022-08-02 10:12:29,625 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2022-08-02 10:12:29,628 Parameters: domain_right_edge         = [10000. 10000. 10000.]
yt : [INFO     ] 2022-08-02 10:12:29,629 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2022-08-02 10:12:29,629 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2022-08-02 10:12:29,630 Parameters: omega_lambda              = 0.73
yt : [INFO     ] 2022-08-02 10:12:29,631 Parameters: omega_matter              = 0.27
yt : [INFO     ] 2022-08-02 10:12:29,631 Parameters: omega_radiation           = 0.0


[('PartType0', 'Coordinates'),
 ('PartType0', 'Density'),
 ('PartType0', 'ElectronAbundance'),
 ('PartType0', 'InternalEnergy'),
 ('PartType0', 'Masses'),
 ('PartType0', 'Metallicity_00'),
 ('PartType0', 'Metallicity_01'),
 ('PartType0', 'Metallicity_02'),
 ('PartType0', 'Metallicity_03'),
 ('PartType0', 'Metallicity_04'),
 ('PartType0', 'Metallicity_05'),
 ('PartType0', 'Metallicity_06'),
 ('PartType0', 'Metallicity_07'),
 ('PartType0', 'Metallicity_08'),
 ('PartType0', 'Metallicity_09'),
 ('PartType0', 'Metallicity_10'),
 ('PartType0', 'Metallicity_11'),
 ('PartType0', 'Metallicity_12'),
 ('PartType0', 'Metallicity_13'),
 ('PartType0', 'Metallicity_14'),
 ('PartType0', 'NeutralHydrogenAbundance'),
 ('PartType0', 'ParticleChildIDsNumber'),
 ('PartType0', 'ParticleIDGenerationNumber'),
 ('PartType0', 'ParticleIDs'),
 ('PartType0', 'SmoothingLength'),
 ('PartType0', 'StarFormationRate'),
 ('PartType0', 'Velocities'),
 ('PartType1', 'Coordinates'),
 ('PartType1', 'Masses'),
 ('PartType1'

### Load the numpy chemistry table

In [39]:
chem_table = np.load('../data/chem_table.npz')
# chem_table.files
print(chem_table['L_CO_1_0'])

[[[[1.81037642e-32 0.00000000e+00 0.00000000e+00]
   [1.81530900e-32 0.00000000e+00 0.00000000e+00]
   [1.81695534e-32 0.00000000e+00 0.00000000e+00]
   ...
   [1.81772382e-32 0.00000000e+00 0.00000000e+00]
   [1.81772103e-32 0.00000000e+00 0.00000000e+00]
   [1.81776297e-32 0.00000000e+00 0.00000000e+00]]

  [[7.22857872e-31 0.00000000e+00 0.00000000e+00]
   [7.31753004e-31 0.00000000e+00 0.00000000e+00]
   [7.34872037e-31 0.00000000e+00 0.00000000e+00]
   ...
   [7.36779540e-31 0.00000000e+00 0.00000000e+00]
   [7.36783775e-31 0.00000000e+00 0.00000000e+00]
   [7.36785451e-31 0.00000000e+00 0.00000000e+00]]

  [[7.69082347e-30 0.00000000e+00 0.00000000e+00]
   [8.90320607e-30 0.00000000e+00 0.00000000e+00]
   [9.69812244e-30 0.00000000e+00 0.00000000e+00]
   ...
   [1.02895869e-29 8.89727086e-39 0.00000000e+00]
   [1.02905916e-29 8.89729363e-39 0.00000000e+00]
   [1.02910033e-29 8.89752481e-39 0.00000000e+00]]

  ...

  [[9.20275444e-30 7.61653650e-29 0.00000000e+00]
   [1.09875331e-